/**
 * Per-device firmware configuration generator. Produces a ready-to-flash
 * config bundle (config.h + secrets.h + README.txt) personalized to a single
 * registered device, zipped with JSZip for one-click download from the
 * device detail page. This does NOT contain the firmware source itself —
 * just the generated headers a builder drops into apps/firmware/include/.
 */
import JSZip from "jszip";
import { downloadBlob } from "./zipExport.js";

// Deployed MQTT broker for this platform instance.
const MQTT_HOST = "178.105.41.164";
const MQTT_PORT = 1883;

function periodLabel(sec) {
  const s = Number(sec) > 0 ? Number(sec) : 3600;
  if (s % 3600 === 0) {
    const h = s / 3600;
    return `${h} hour${h === 1 ? "" : "s"}`;
  }
  if (s % 60 === 0) {
    const m = s / 60;
    return `${m} minute${m === 1 ? "" : "s"}`;
  }
  return `${s} seconds`;
}

function buildConfigHeader(device) {
  const siteId = device.siteId || "SITE_ID";
  const devId = device.devId || "DEV_ID";
  const periodSec = Number(device.telemetryPeriodSec) > 0 ? Number(device.telemetryPeriodSec) : 3600;
  const periodMs = Math.round(periodSec * 1000);
  const lat = device?.location?.lat;
  const lon = device?.location?.lon;
  const address = device?.location?.address;

  return `#pragma once
/*
 * K2U monitoring firmware configuration
 * Generated for device: ${devId}  (site: ${siteId})
 * Generated at: ${new Date().toISOString()}
 *
 * Deployment location (reference only — not transmitted by the firmware):
 *   lat:     ${Number.isFinite(lat) ? lat : "—"}
 *   lon:     ${Number.isFinite(lon) ? lon : "—"}
 *   address: ${address || "—"}
 */

#define SITE_ID "${siteId}"
#define DEV_ID  "${devId}"

// Telemetry publish interval. Device publishes to:
//   site/${siteId}/dev/${devId}/telemetry
#define TELEMETRY_PERIOD_MS ${periodMs}UL

// GOST 32144-2013 voltage-unbalance (K2U) thresholds, percent.
#define GOST_K2U_NORMAL_PCT 2.0
#define GOST_K2U_MAX_PCT    4.0

// Pin map
#define PZEM_RX_PIN    16
#define PZEM_TX_PIN    17
#define I2C_SDA_PIN    21
#define I2C_SCL_PIN    22
#define STATUS_LED_PIN 2

// PZEM-004T Modbus slave addresses, one per phase (A/B/C).
#define PZEM_ADDR_A 0x01
#define PZEM_ADDR_B 0x02
#define PZEM_ADDR_C 0x03
`;
}

function buildSecretsHeader(device) {
  const siteId = device.siteId || "SITE_ID";
  const devId = device.devId || "DEV_ID";

  return `#pragma once
/*
 * WiFi + MQTT secrets for device ${devId}. Fill in your WiFi credentials
 * before flashing. Do NOT commit this file to version control.
 *
 * MQTT settings below are pre-filled for the K2U platform deployment this
 * device is registered against.
 */

#define WIFI_SSID     "your-ssid"
#define WIFI_PASSWORD "your-wifi-password"

#define MQTT_HOST "${MQTT_HOST}"
#define MQTT_PORT ${MQTT_PORT}
#define MQTT_USER "${devId}"
#define MQTT_PASS "change-me"

// This device publishes telemetry to topic:
//   site/${siteId}/dev/${devId}/telemetry
`;
}

function buildReadme(device) {
  const devId = device.devId || "DEV_ID";
  const siteId = device.siteId || "SITE_ID";

  return `K2U firmware configuration — device ${devId}
=================================================

This archive was generated by the K2U monitoring dashboard for device
"${devId}" (site "${siteId}"). It contains a personalized config.h and a
secrets.h template — not the firmware source.

Setup:
  1. Clone the firmware repository:
       git clone https://github.com/sherbaev/k2u
  2. Copy config.h and secrets.h from this archive into:
       apps/firmware/include/
  3. Open secrets.h and fill in WIFI_SSID / WIFI_PASSWORD for the site's
     WiFi network.
  4. Build and flash with PlatformIO:
       pio run -e esp32dev -t upload

Publishing interval: ${periodLabel(device.telemetryPeriodSec)}.
Broker: ${MQTT_HOST}:${MQTT_PORT} (plaintext; 8883 for TLS)
Topic:  site/${siteId}/dev/${devId}/telemetry
`;
}

/** Build the personalized firmware config ZIP for a device. @returns {Promise<Blob>} */
export async function buildFirmwareZip(device) {
  const zip = new JSZip();
  const include = zip.folder("include");
  include.file("config.h", buildConfigHeader(device || {}));
  include.file("secrets.h", buildSecretsHeader(device || {}));
  zip.file("README.txt", buildReadme(device || {}));
  return zip.generateAsync({ type: "blob" });
}

/** Build and trigger a browser download of the firmware config ZIP for a device. */
export async function downloadFirmwareZip(device) {
  const blob = await buildFirmwareZip(device);
  const devId = device?.devId || "device";
  downloadBlob(blob, `firmware-${devId}.zip`);
}
